### ISSUE TITLE
flex-basis揭秘

### ISSUE THREAD

**Issue by FE-wuhao** [FE-wuhao/TrivialKnowledge#19]
* 使用对象
  **item**而不是container
<div><img src="https://user-images.githubusercontent.com/39676031/90225924-c60b6780-de44-11ea-9287-bf7cc6ec7695.png"
 width="400px" />
<img src="https://user-images.githubusercontent.com/39676031/90225939-c86dc180-de44-11ea-9e6b-090cc2c62222.png"
 width="400px" /></div>

* 作用
在container进行**最终空间分配**（根据flex-grow和felx-shrink分配大小）之前确定item自身的尺寸
* 默认值：
  * 直接使用flex-basis的情况下默认值为`auto`
  * 使用flex的情况下,如`flex:1`,flex-basis的默认值为`0%`
* 值类型
根据MDN的兼容性报告来看，flex-basis正常人能用得上的三种值类型为：auto、具体值(px)、百分比
  * **auto:** 根据item的实际内容来决定尺寸。比方说一个div，里面装的字越多，auto分配给他的大小也就越大。auto分配完item的尺寸以后，flex容器根据item们的flex-grow和flex-shrink数值，集体性放大缩小，最终决定尺寸
```html
// html
<div id='container'>
  <div id='item1'>1</div>
  <div id='item2'>2</div>
  <div id='item3'>3</div>
</div>
```

```css
// css
#container{
  width:500px;
  height:300px;
  background-color:orange;
  display:flex;
  flex-flow:nowrap column;
}
#item1{
  background-color:red;
  flex:1 ;
}
#item2{
  background-color:green;
  flex:1;
}
#item3{
  background-color:purple;
  flex:1  auto;
}
```
  效果图
<img src="https://user-images.githubusercontent.com/39676031/90229958-59e03200-de4b-11ea-9fb4-9151e06b117c.png"
 width="400px" />
  **分析：** `flex:1`等同于`flex:1 1 0%`，即这里`flex-basis:0%`，`flex:1 auto`等同于`flex:1 1 auto`，即这里`flex-basis:auto`。0%为父元素高度的0%，即0px；auto为item内容的高度，即这个div中‘3’的高度，按照图中尺寸计算的'3'的高度为20px，合理！

  * **具体值：** 具体定夺item的大小。打个比方，给一个div设定它的flex-basis为50px，那么在进行最终的集体放大/缩小之前，这个div的尺寸就是50px了，进行最终空间分配的时候他就会比那些使用`flex-basis:0px`的div长50px

```html
// html
<div id='container'>
  <div id='item1'>1</div>
  <div id='item2'>2</div>
  <div id='item3'>3</div>
</div>
```

```css
// css
#container{
  width:500px;
  height:300px;
  background-color:orange;
  display:flex;
  flex-flow:nowrap column;
}
#item1{
  background-color:red;
  flex:1 ;
}
#item2{
  background-color:green;
  flex:1;
}
#item3{
  background-color:purple;
  flex:1  200px;
}
```
  效果图
<img src="https://user-images.githubusercontent.com/39676031/90229763-053cb700-de4b-11ea-8dcb-a162c9e1d622.png"
 width="400px" />
  **分析：** `flex:1`等同于`flex:1 1 0%`，即这里`flex-basis:0%`，`flex:1 200px`等同于`flex:1 1 200px`，即这里`flex-basis:200px`。0%为父元素高度的0%，即0px；200px即设定item3的默认高度是200px，container高度为300px，剩余均分`(300-200)/3=33.3`，由此可得item1高度为`33px`，item2高度为`33px`，item3高度为`200px+33px=233px`，与效果图中尺寸一致，perfect！

  * **百分比：** 相对于父元素的容器的大小，即`item宽/高=容器宽/高*百分比`。flex的默认值中flex-basis就是0%，即没有高度，此时众生平等，不管你的内容有多少，只要在一个容器里，大家所分得的宽/高都是一样的。
```html
// html
<div id='container'>
  <div id='item1'>1</div>
  <div id='item2'>2</div>
  <div id='item3'>3</div>
</div>
```

```css
// css
#container{
  width:500px;
  height:300px;
  background-color:orange;
  display:flex;
  flex-flow:nowrap column;
}
#item1{
  background-color:red;
  flex:1 ;
}
#item2{
  background-color:green;
  flex:1;
}
#item3{
  background-color:purple;
  flex:1  50%;
}
```
  效果图
<img src="https://user-images.githubusercontent.com/39676031/90230274-e2f76900-de4b-11ea-8093-877ce4104a20.png"
 width="400px" />
  **分析：** `flex:1`等同于`flex:1 1 0%`，即这里`flex-basis:0%`，`flex:1 50%`等同于`flex:1 1 50%`，即这里`flex-basis:50%`。0%为父元素高度的0%，即0px；50%为父元素高度的50%，即`300*50%=150px`，剩余均分`(300-150)/3=50`，由此可得item1高度为`50px`，item2高度为`50px`，item3高度为`150px+50px=200px`，与效果图中尺寸一致，perfect！

* 最后演示一下众生平等，同时我也特意更改一下item3的内容长度
```html
// html
<div id='container'>
  <div id='item1'>1</div>
  <div id='item2'>2</div>
  <div id='item3'>3333333333</div>
</div>
```

```css
// css
#container{
  width:500px;
  height:300px;
  background-color:orange;
  display:flex;
  flex-flow:nowrap column;
}
#item1{
  background-color:red;
  flex:1 ;
}
#item2{
  background-color:green;
  flex:1;
}
#item3{
  background-color:purple;
  flex:1 ;
}
```

  效果图
<img src="https://user-images.githubusercontent.com/39676031/90232011-9b261100-de4e-11ea-8f23-a0779742ab23.png"
 width="400px" />

  **分析：** `flex:1`等同于`flex:1 1 0%`，即这里`flex-basis:0%`,0%为父元素高度的0%，即0px.此时大家均分父元素的高度`300/3=100`，由此可以推出item1,item2,item3的高度都是`100px`，与效果图中尺寸一致，perfect！

**Comment by FE-wuhao** [comment]
### 特殊情况：item高度超过container分配给他的高度

```html
// html
<div id='container'>
  <div id='item1'>1</div>
  <div id='item2'>2</div>
  <div id='item3'>
    <div>233</div><div>233</div>               
    <div>233</div><div>233</div>               
    <div>233</div><div>233</div>               
    <div>233</div><div>233</div>
  </div>
</div>
```

```css
// css
#container{
  width:500px;
  height:300px;
  background-color:orange;
  display:flex;
  flex-flow:nowrap column;
}
#item1{
  background-color:red;
  flex:1 ;
}
#item2{
  background-color:green;
  flex:1;
}
#item3{
  background-color:purple;
  flex:1 ;
}
```
  效果图
<img src="https://user-images.githubusercontent.com/39676031/90233173-4c797680-de50-11ea-9ba4-bc925a49d99b.png"
 width="400px" />

  **分析：** 按道理应该大家都分得100px的高度，但这里item3内容太多了，100px已经装不下了，只能给item3多分点高度，其他俩兄弟啃啃窝窝头了，所以最终高度的分配如上图所示。

* 思考
  这种情况下有让他们均分高度的可能吗？答案是肯定的，我们只需要在item3的样式中添加`overflow:hidden`或者`overflow:scroll`即可再次回到众生平等的公平状态了。前者是直接隐藏溢出的内容，后者是添加滚动条，这个自己根据业务场景判断选择哪种处理方式比较OK。添加上述两种处理方式的效果图如下所示：
<div>
<img src="https://user-images.githubusercontent.com/39676031/90233636-07097900-de51-11ea-9dba-9357418b29ca.png"
 width="400px" />
<img src="https://user-images.githubusercontent.com/39676031/90233678-15f02b80-de51-11ea-907e-a72e29a90708.png"
 width="400px" />
</div>
